# singleTypes:
#     # fetches only the most recently updated entry in a particular content type
#     # Generated file will be named after the fileName setting
#     - id: homepage
#       directory: /content/
#       fileName: _index
#       fileExtension: md

#       # this will generate a file named "_index.md" in the "content" directory
#     - id: siteSettings
#       directory: /data/
#       fileName: settings
#       fileExtension: yaml
#       # this will generate a file named settings.yaml in the "data" directory

repeatableTypes:
    # fetches all the entries of a content type and places them in a directory.
    # Generated files will be named after their Entry ID in Contentful.
    - id: posts
      directory: /content/posts/
      fileExtension: md
      mainContent: content
    - id: category
      directory: /content/category/
      fileExtension: md
      mainContent: content


    # - id: seoFields
    #   isHeadless: true
    #   directory: /content/seo-fields/

    # - id: categories
    #   directory: /content/categories/
    #   fileExtension: md
    #   mainContent: category
